[workspace]
authors = ["glachaud <guillaume.lachaud@polytechnique.edu>"]
channels = ["conda-forge"]
name = "lab_7"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
lab = "marimo edit notebook.py"

[dependencies]
python = ">=3.11"

[pypi-dependencies]
lab-x = { path = ".", editable = true }
